language: java
addons:
  apt:
    packages:
    - xmlstarlet
    - graphviz
jdk:
- oraclejdk11
after_success:
- wget -O settings.xml https://raw.githubusercontent.com/pousse-cafe/pousse-cafe-deploy/master/snapshot_release_settings.xml
- ./can_auto_deploy.sh && mvn deploy --settings settings.xml
env:
  global:
  - secure: VoQv7FMcKRuTugTAHvIVA0tvCIRorh8yQvHrg6idis4JYUu/RFFqz4B9ElxVcwDi6DTvqwSUJ8xVi76gmnfMLTe0PXFfFHVF5B3/rDkQdr8ItLZiQLwV/UNQuionT7Wh47nDDA8n+fj9F/MejDTZQJQyIxhRlGwEV5Kg7RvaC5Vy/dgU+kHk+Qb50Z5SmLuGOhsl9wz9gLOz9DhQ84Cow86xIPSzKfxWUrkfaP+v0Z7bnUy7y5rG0f+uwpO0T+eiSrvEIhsSjjXOv3hZIR12EfXCMmm/znX1HfaWvAEGYPPky0aByncKpogIjPL3nFjUff9FUjNHX5AMyi/g7xB8IHkhzJe3NRZfQHLFtsRRwpLhJWJGhOLGYmS8n87nnH4xmoItOVHHPfM0ieR5th5Ggoe/hGJJQrXInawWD6Ef+T0NUSKK57QuaOPprRFiyWIeIqMjlrIHIpHRWfc06leoboGH1Go69+HQgm/KF+UW27VS5bNxjlggfwdPPJJYpJVvC1AWGWmD8rFjMPj/qBipyr9d5xigWJ899JaITLN74ua0pahcPi8yLm6xV14W/xUYkVTHNou6rxHoaXtXwpN0zVGLZ7h3kxcTtX0MdwcxGOrkiq2TRopGXumApjIhAAvAvYxmHSSLznPYP2b5mnGckOiIGTp+oI76wunAUAx470Q=
  - secure: HSpJIzMpKpoloIOFcq+rwOPCDVeQiDsIf7uA2psboMq+W6TNSVeJ58L6Pu14hDDIDynTFLLiDvhKmWQEnXZYfCBDfKSq3qsvveRYTC0STM35pgfJicHUnuvM2A3U3JnUzBeenphmLhLyIkX4QkC9jJWbWtSKduu4LdurctD4wJ/Y1CNaNYQ/cK5vSKGMGVyW0mkDijx/7Aa3stUT7OKfBXT7vKaCAvnUFc7n9r7nHUyNr1QhR/QQpucRyokIJZgUqn9B7frnlifm3skd5UZUitwmzWfTzVC7drgXcLlXn+epNHTXD6czvtqIJpuxIhZaSE8Nqk/H6AVSmVj63pS4qg4uzyqwjU6awY8/8ALAA4VQ0SjvpciobKUf/yB4nnoegp0iqXczrkNTi8ge6ELG/Ueb0IIp++y9+GAWFwpa0Q4NIo1/MfBWCkhxQj2OhoWrsQlEPz6AMbxoatzSCXfyiCtJliMgKlmgc3bAiYyJi1ahSRfhy8sxgWzJZ5fQu8Kcd1LDSvRSX6gwT/M9BfGPIfXOdmAfLmgsPLxcDhQzYRFQgNPZ3lMCsEQGlg5V/3mdSj8KkHTcZBYFYJUMFYdpqPhElp0FI0otBdy0yCwg3KPAuzuUGbQSfg+kLpYt0SlmMF3/0OT+HMXiBIxUEhvyFh6B86qroqiwUOY6ca0bnhg=
